#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 18 19:00:35 2018

@author: natalie
"""
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
import psycopg2

myfile='/home/natalie/Documents/Manifold/data/CIDDS-002/traffic/week1.csv'
c_size=100000
#pd.read_csv(myfile,chunksize=c_size)

username = 'postgres'
password = 'Natbou42'     # change this
host     = 'localhost'
port     = '5432'            # default port that postgres listens on
db_name  = 'manifold'

## 'engine' is a connection to a database
## Here, we're using postgres, but sqlalchemy can connect to other things too.
engine = create_engine( 'postgresql://{}:{}@{}:{}/{}'.format(username, password, host, port, db_name) )
print(engine.url)

## create a database (if it doesn't exist)
if not database_exists(engine.url):
    create_database(engine.url)
print(database_exists(engine.url))

df_list=[]
for gm_chunk in pd.read_csv(myfile, chunksize=c_size, low_memory=False):
    gm_chunk.to_sql('manitable', engine, if_exists='append')
    #df_list.append(gm_chunk)
    
con = None
con = psycopg2.connect(database = db_name, user = username, host = 'localhost', password='Natbou42')

sql_query = """
SELECT * FROM manitable limit 5;
"""
first5_data_from_sql = pd.read_sql_query(sql_query,con)
first5_data_from_sql.head()